** Les mécanismes internes de l'Orfeo ToolBox                        :slides:
*** Slide
** Les mécanismes internes de l'*Orfeo ToolBox*                     :guide:
*** Description                                                        :desc:
**** Résumé
     
     Cet exercice permet de se familiariser avec les mécanismes
     internes de l'Orfeo ToolBox:
     - Les noms de fichier étendus,
     - Le streaming,
     - Le multi-threading,
     - Les variables d'environnements
     - Les fichiers geom

     
**** Pré-requis

     - Logiciels installés (Monteverdi et Orfeo ToolBox)
     - Données téléchargées
     - Connaisance du mécanisme des applications de l'Orfeo ToolBox (voir exercice correspondant)

**** Objectifs
     
     - Comprendre les mécanismes transparents de l'Orfeo ToolBox
     - Savoir influencer la manière dont l'Orfeo ToolBox exécute un traitement
     - Savoir ou trouver des informations complémentaires

*** Étapes                                                            :steps:

**** Encodage des images

     Dans l'Orfeo ToolBox, c'est l'utilisateurs qui choisit le type
     d'encodage des images en fonction de ce que l'image
     représente. Ainsi, on choisira en général:
     - Un encodage entier sur 8 bits non-signés (plage de valeurs
       [0,255]) pour des sorties destinées à un affichage ou des
       rapports,
     - Un encodage entietre sur 16 bits non signés pour représenter
       des images satellites,
     - Un encodage flottant (32 ou 64 bits) quand on représente le
       résultat d'un calcul produisant des nombres réels (NDVI,
       calibration radiométrique ...).

       Dans les applications de l'Orfeo ToolBox, l'utilisateur peut
       choisir simplement son encodage (menu déroulant dans les
       interfaces graphiques ou paramètre additionnel en ligne de
       commande).
       
       #TODO: A continuer
       

**** Les fichiers .geom

     Examinez le contenu du fichier /image.geom/. Que pouvez vous en
     conclure quand à son rôle? Quelles sont les opérations
     nécessitant ce type d'informations ?

**** Les noms de fichiers étendus

     Les noms de fichiers étendus permettent d'influencer la manière
     dont l'Orfeo ToolBox lit ou écrit une image. Ils ne sont pas
     spécifiques aux applications, mais peuvent être utiliser pour
     n'importe quel logiciel construit autour de l'Orfeo ToolBox.
     
     L'ensemble des options disponibles sont listées dans la section
     7.10 du Software Guide. Nous allons illustrer leurs
     fonctionnement en nous concentrant sur quelques options.

***** Les options de lecture

      #TODO: Données à préparer

      Comparez les sorties des deux commandes suivantes:

      #+BEGIN_EXAMPLE
      $ otbcli_ReadImageInfo -in "image1.tif"
      $ otbcli_ReadImageInfo -in "image1.tif?&skipgeom=true"
      #+END_EXAMPLE

      Quel est l'effet du paramètre /skipgeom/ ? Notez son
      équivalent /skicarto/, qui permet de s'affranchir de la
      projection cartographique grossière dans le cas des produits de
      type ortho-ready.

      Comparez les sorties des deux commandes suivantes:
      
      #+BEGIN_EXAMPLE
      $ otbcli_ReadImageInfo -in "image2.tif"
      $ otbcli_ReadImageInfo -in "image2.tif?&geom=image1.geom"
      #+END_EXAMPLE

      Quel est l'effet du paramètres /geom/ ? Quel peut être son utilité ?

***** Les options d'écriture

      
      

**** La gestion du streaming

**** Le multi-threading


** Les mécanismes internes de l'*Orfeo ToolBox*                   :solutions:

