** Le mécanisme des applications Orfeo TooLBox                       :slides:
*** Test1
*** Test2
** Le mécanisme des applications *Orfeo ToolBox*                      :guide:
*** Description                                                        :desc:
**** Résumé
     
     Au cours de cette excerice, nous allons apprendre à utiliser les
     applications de l'Orfeo ToolBox. Des images intégrants des
     messages codés par stéganographie vous sont proposées. A vous
     d'utiliser les applications de l'Orfeo ToolBox afin de révéler le
     message contenu dans les images.
     
     Toutes les images d'origine utilisées dans cet exercice sont des
     extraits d'images Pléiades.

**** Pré-requis
     
     - Logiciels installés (Monteverdi et Orfeo ToolBox)
     - Données téléchargées
     
**** Objectifs

     - Savoir rechercher une application dans la liste des
       applications disponibles
     - Savoir paramétrer une application
     - Savoir trouver la documentation d'un application
     - Savoir utiliser plusieurs applications classiques

*** Étapes                                                            :steps:
**** Message 1    

     Dans l'image /message1.tif/, une phrase a été encodée dans une
     zone de forte réflectance, en utilisant une valeur de pixel qui
     n'est pas admissible pour Pléiades (rappel: les images Pléiades
     sont codées sur des entiers de 12 bits non signés).

     Utilisez l'application *BandMath* pour détecter ces valeurs
     abhérentes et ainsi révéler le message.

**** Message 2

     Dans l'image /message2.tif/, une phrase à été encodée dans une
     zone homogène de faible luminance. Les pixels ainsi modifiés ne
     sont pas détectables à l'oeil nu, mais pourraient être révélé par
     l'application d'un gradient ou d'un détecteur de contour.

     Utilisez l'application *EdgeDetection* pour révéler le message.

**** Message 3

     Dans l'image /message3.tif/, une phrase a été encodée en
     modifiant légèrement les valeurs des pixels des bandes rouge et
     proche infra-rouge. Cette modification est invisile à l'oeil nu,
     mais peut être révélée en calculant l'indice de végétation NDVI.

     Utilisez l'application *RadiometricIndices* pour révéler le message.

     Alternativement, utilisez l'application *BandMath* pour calculer
     l'indice NDVI à l'aide de la formule suivante:
     
     \begin{center}
     $NDVI = \frac{NIR-RED}{NIR+RED}$
     \end{center}

**** Message 4

     Dans l'image /message4.tif/, un message a été dissimulé dans les
     2 bits de poids faible de l'image. Cette transformation est
     indétectable à l'oeil nu, mais pourrait être révélé en isolant la
     valeur de ces 2 bits.

     Utilisez l'application *BandMath* pour isoler les 2 bits de poids
     faible dans l'image (encodée sur 12 bits pour rappel), afin de
     faire apparaître le message.

**** Message 5

     Dans l'image /message5.tif/, un message a été dissimulé en
     modifiant légèrement et localement le bruit de l'image. Il
     pourrait être révélé par une transformation permettant d'isoler
     le bruit.

     Utiliser l'application *DimensionalityReduction* pour isoler le
     bruit de l'image et ainsi révéler le message.

     Eventuellement, imaginer d'autres procédés utilisant les
     applications pour mettre en évidence cette modification locale du
     bruit.

**** Message 6

     Dans l'image /message6.tif/, un message a été dissimulé en
     utilsant localement un opérateur morphologique en niveaux de gris
     (ouverture). Il pourrait être révélé en utilisant la propriété
     d'idempotence de cette transformation. Pour rappel, une fonction
     $f$ est dite idempotente si:

     \begin{center}
     $f(f(x))=f(x)$
     \end{center}

     Utilisez les applications *GrayscaleMorphologicalOperation* et
     *BandMath* pour révéler le message en vous appuyant sur la
     propriété d'idempotence.

*** Pour aller plus loin                                            :further:

    Quelles messages étaient détectables en analysant finement l'image
    avec Monteverdi? Quelles messages ne l'étaient pas?

    Pouvez vous imaginer d'autres procédés pour incruster des messages
    indétectables dans les images? Une image (/image.tif/) et un
    message sous la forme d'une image binaire (/message.tif/) vous
    sont fournies pour vous exercer.

*** Solutions                                                     :solutions:

