** Introduction au traitements des images RSO :slides:
*** Objectifs et Données
**** Objectifs
     - Savoir manipuler des images
     - Savoir réaliser une calibration radiométrique
     - Savoir utiliser le filtrage du speckle
     - Savoir réaliser une analyse polarimétrique simple
     - Savoir réaliser une extraction de primitives simple

**** Données
     Les données pour cet exercice se trouvent dans le répertoire /sar/.

*** Déroulement
    1. Introduction à l'imagerie RSO
    2. Calibration radiométrique
    3. Filtrage du speckle
    4. Polarimétrie
    5. Extraction d'information

*** Introduction SAR
    - RSO: Radar à Synthèse d'Ouverture (SAR en anglais)
    - Impulsions hyperfréquences et enregistrement des échos
    - Quasi-transparence de l'atmosphère
*** Principe de fonctionnement
    - 1 antenne réalise des impulsions micro-ondes dans le plan perpendiculaire à la trajectoire du porteur
    - Echo recueilli par la meme antenne
    - Relfecteur sont localisés en fonction de leur eloignement (distance)
    - Répétition des échos réalise la deuxième dimension (azimuth)
    - signal  reçu  par  le  radar  est caractérisé  par  son  amplitude  et  sa  phase
*** Radiométrie
    - comportement de la réflexion dépend des caractéristiques de la surface
    - notamment de sa rugosité, de l'humidité des sols
    - Notion de polarimétrie

*** Pour aller plus loin
    - S1 ToolBox (SNAP)
    - Polarimétrie: ESA PolSARPro

** Introduction au traitements des images RSO                         :guide:
*** Description                                                        :desc:
**** Résumé
     Cet exercice constitue une introduction au traitement et à l'analyse des
     images RSO (radar à synthèse d'ouverture) en utilisant l'Orfeo ToolBox.

**** Pré-requis

     - Logiciels installés (Monteverdi et Orfeo ToolBox)
     - Données téléchargées
     - Connaisance du mécanisme des applications de l'Orfeo ToolBox (voir
       exercice correspondant)

**** Objectifs
     Les objectifs de cet exercice sont les suivants:
     - Savoir manipuler des images
     - Savoir réaliser une calibration radiométrique
     - Savoir utiliser le filtrage du speckle
     - Savoir réaliser une analyse polarimétrique simple
     - Savoir réaliser une extraction de primitives simple

*** Étapes                                                            :steps:
**** Introduction à l'imagerie RSO

Dans cette exercice nous utiliserons les extraits de l'image Sentinel 1 SLC :
~s1_hh.tif~ et ~s1_hv.tif~. L'image se situe en Allemagne au sud de la ville
d'Ulm près du lac Constance (47.456276, 9.638616).

Les extraits sont en géométrie capteur et sont inversées dans le sens EST/OUEST

1. Ouvrir les images dans Monteverdi. A quoi correspondent les 2 images combien de bandes possèdent-elles?
2. A quoi correspondent ces bandes? 
3. Calculer l'image d'intensité à partir des produits complexes  ~s1_hh.tif~ et ~s1_hv.tif~.

**** Calibration radiométrique
     Les valeurs des pixels dans les produits SAR comme Sentinel-1 sont sans
     unité (radar reflectivity or radar brightness).

     Le produit est accompagné de métadonnées permettant de transformer ces
     valeurs en grandeur physique qui permettent d'intercomparer des images
     radars provenant de capteurs différents ou de capteurs identiques utilisés
     dans différents modes. 

     On peut de l'image d'entrée les caractéristiques physiques originales des
     valeurs de rétrodiffusion. Les valeurs suivantes peuvent etre calculées:
     - beta zero: luminosité radar (slant range)
     - sigma zero: rétrodiffusion radar (directement relié au propriété du sol)
     - gamma zero: rétrodiffusion radar normalisée par l'angle d'incidence (à privilégier généralement ) 

     Pour Sentinel-1 est fourni une table de
     valeur permettant de faire la conversion depuis les comptes numérique vers
     ces différentes grandeurs.

     1. Quelle application permet d'effectuer cette opération dans l'OTB?
     2. Effectuer la calibration des extraits complexes HH et HV et calculer les grandeurs
        gamma zero (gamma naught en anglais). Attention, le fichier geom n'est
        pas reconnu automatiquement dans l'application. Il faut utiliser
        l'option de fichier étendu "&geom=" en entrée. 
     3. Convertir l'image gamma zero en dB.

**** Filtrage du speckle
     Les images SAR sont fortement affectées par le chatoiement (speckle) qui constitue un
     type particulier de bruit présent dans tous les systèmes d'acquisition cohérent
     (sonar, laser, etc.). Ce bruit est très fort et il a un effet multiplicatif.

     Il existe plusieurs méthodes pour réduire ce bruit. Dans la suite nous
     allons utiliser le filtre de /Frost/ qui possède 2 paramètres: rayon: taille de la fenetre
     et /deramp/ qui controle la décroissance d'une fonction exponentiel qui est
     utilisé pour pondéré la distance entre le pixel central et son voisinage.

     Plus de détail sur le speckle et le filtre de Frost [[http://earth.eo.esa.int/download/eoedu/Earthnet-website-material/to-access-from-Earthnet/2011_ESA-CONAE-SAR-Capacity-Building-Argentina/Speckle.pdf][ici]].

     1. Quelle sont les méthodes de réduction du speckle disponible dans l'OTB?
     2. Utilisez le filtre de Frost avec différents rayons (3,5 et 10) et
       commentez l'effet sur l'image de sortie
     3. Commentez la forme de l'histogramme des images filtrées comparé à
        l'image d'intensité?
     4. Utilisez le filtre de Frost avec un rayon de 5 et différentes valeurs
        du paramètre /deramp/ (00.5,0.2 et 0.8). Commentez l'effet de ce paramètre.

**** Polarimétrie
     Nous allons comparer de manière qualitative la différence entre les
     observations des images en polarimétries HH et HV pour détecter certains
     éléments dans l'image.

     1. Calculez la différence entre l'image d'intensité HH et HV. On peut
        prendre 2 fois HV car la valeur rétrodiffusée en HV est généralement
        inférieur. Sur cette image je propose d'utiliser la différence simple HH-HV
     2. Effectuez une composition colorée avec les bandes HH, HV et HH-HV. On peut
        prendre 2 fois HV car la valeur rétrodiffusée en HV est généralement inférieur.
     3. Convertissez la composition colorée en Décibel (Db)
     4. Affichez le résultat avec Monteverdi et commentez les différences entre
        HH et HV (zone de layover, zone de végétation, sol nu, zone en eau...)
     5. Jouons un peu pour fournir à "Où est Charlie?" à partir de la
        composition colorée en Décibel:
        - Indiquer les coordonnées de 2 lignes électrique parallèle visible dans l'image?
        - Plus dur, chercher dans l'image une zone réagissant comme un coin réflecteur
          ("croix").
        - A quoi correspondent les "points" en violet dans le lac autour des
          coordonnées (930,1170)?

        Vous pouvez pour faciliter l'analyse visualisez la zone d'étude dans
        [[https://www.google.fr/maps/place/47%C2%B027'51.0%22N+9%C2%B036'22.5%22E/@47.462655,9.5676349,18957m/data=!3m1!1e3!4m2!3m1!1s0x0:0x0][Google Maps]].

        Et aussi remettre les images en Ouest/Est avec par exemple l'outil
        ImagMagick:

        #+BEGIN_EXAMPLE
        convert input.tif -depth 32 
        -define quantum:format=floating-point 
        -flop output.tif
        #+END_EXAMPLE
**** Extraction d'information

     Pour aller plus loin on pourra ensuite explorer les primitives et les
     algorithmes disponibles pour l'extraction de données dans les images SAR.

     Voir filtre de Touzi dans l'application *EdgeExtraction* par exemple.

** Introduction au traitements des images RSO :solutions:
**** Introduction à l'imagerie RSO
1. Les 2 extraits correspondent respectivement à la combinaison polarimétrique
   HH (transmission et réception horizontales) et HV (transmission horizontale et réception verticale).
2. Ces bandes correspondent respectivement à la partie réelle et partie
   imaginaire su signal radar?
3. On peut utiliser l'application *BandMath* pour réaliser le calcul de l'image d'intensité:

   Pour HH:

   #+BEGIN_EXAMPLE
    $ otbcli_BandMath -il s1_hh.tif 
                      -out intensity_hh.tif int32 
                      -exp "im1b1*im1b1+im1b2*im1b2"
   #+END_EXAMPLE

   Pour HV:

   #+BEGIN_EXAMPLE
    $ otbcli_BandMath -il s1_hv.tif 
                      -out intensity_hv.tif int32 
                      -exp "im1b1*im1b1+im1b2*im1b2"
   #+END_EXAMPLE

**** Calibration radiométrique
     1. *SarCalibration*
     2. Pour Sentinel-1 les coefficients de calibration sont lus automatiquement
        dans les métadonnées du produit:
        #+BEGIN_EXAMPLE
        $ otbcli_SarRadiometricCalibration -in "s1_hh.tif?&geom=s1_hh.geom"
                                           -out s1_hh_gamma0.tif
                                           -lut gamma
        #+END_EXAMPLE

        Idem pour l'extrait en polarisation HV
        
     3. Attention au pixel <= 0 dans l'expression du log!

        #+BEGIN_EXAMPLE
        $ otbcli_BandMath -in s1_hh_gamma0.tif
                          -out s1_hh_gamma0_db.tif
                          -exp "im1b1>0?10*log10(im1b1):0"
        #+END_EXAMPLE

**** Filtrage du speckle

     1. Les méthodes disponibles sont: lee, frost, kuan et gamma map. Quelque
        soit la méthode utilisée on note une amélioration majeure de la qualité
        de l'image filtrée qui permet d'identifier des structures difficilement
        visible dans l'image d'intensité originale. 

     2. Réduction du speckle avec l'algorithme de Frost:

        #+BEGIN_EXAMPLE
        $ otbcli_Despeckle -in intensity_hh.tif 
                           -out intensity_hh_speckle.tif 
                           -filter frost 
                           -filter.frost.rad 3
        #+END_EXAMPLE

        L'augmentation du rayon a pour effet d'augmenter le lissage de l'image
        fitlrée. Cela permet d'améliorer la qualité des images dans les zones
        homogènes mais entraine également la perte d'information et de détail
        sur des petites structures avec beaucoup de contraste. 

     3. L'histogramme des images filtrées tend à devenir gaussien (en cloche) et
        va progressivement différer de la distribution Gamma de l'image
        originale (la loi Gamma se caractérise par une distribution en cloche
        asymétrique avec une longue queue à droite) .
     4. L'augmentation du paramètre /deramp/ diminue la décroissance de
        l'atténuation exponentielle et à donc tendance à prendre plus en compte
        les pixels éloignés du pixel central ce qui augmente l'effet de lissage
        sur l'image filtrée.

**** Polarimétrie
     1. Calcul de la différence HH-HV:
        #+BEGIN_EXAMPLE
      $ otbcli_BandMath -il intensity_hh_speckle.tif intensity_hv_speckle.tif
                        -out hh-hv_speckle.tif -exp "im1b1-2*im2b1"
        #+END_EXAMPLE
     2. On effectue ensuite la concaténation entre les polarisations croisées et la
        différence des 2:
     #+BEGIN_EXAMPLE
      $ otbcli_ConcatenateImages -il intensity_hh_speckle.tif
                                 intensity_hv_speckle.tif hh-hv_speckle.tif 
                                 -out intensity_compo.tif 
     #+END_EXAMPLE
     1. Attention au pixel <= 0 dans l'expression du log!

        #+BEGIN_EXAMPLE
        $ otbcli_BandMath -in intensity_compo.tif
                          -out intensity_compo_db.tif
                          -exp "im1b1>0?10*log10(im1b1):0"
        #+END_EXAMPLE
     2. Commentaires:
        - layover: correspond à un effet géométrique réponse similaire HH et HV
        - variabilités traduisent aussi des différences de type et de niveau de croissance des végétations et d’humidité du sol
        - zone de végétation (foret): vert/jaune
        - HV moins sensible à la rugosité
        - Zone en eau: réponse radar faible (HH)
     3. Analyse de la composition colorée:
        - Lignes électriques parallèles autour des coordonnées image (230,3700)
        - Coin réflecteur au coordonnée image (3620,2925)
        - Plot métaliques pour amarrer les bateaux 
     
