#+TITLE: Exploit Pleiades PHR data with the ORFEO ToolBox \\ Updated for OTB-4.2
#+AUTHOR: Manuel Grizonnet (CNES), Julien Michel (CNES), Jordi Inglada (CNES)
#+OPTIONS: H:4
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a4paper,11pt,twoside,openright]
#+LaTeX_HEADER: \usepackage{a4wide}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{mathptmx}
#+LaTeX_HEADER: \usepackage[scaled=.90]{helvet}
#+LaTeX_HEADER: \usepackage{courier}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{ulem}
#+OPTIONS: tags:nil

#+SELECT_TAGS:
#+EXCLUDE_TAGS:

#+LATEX:\pagestyle{fancy}
#+LATEX:\fancyhf{}
#+LATEX:\fancyhead[LE,RO]{\bfseries\thepage}
#+LATEX:\fancyhead[LO]{\bfseries\rightmark}
#+LATEX:\fancyhead[RE]{\bfseries\leftmark}
#+LATEX:\fancyfoot[LE,RO]{\vspace{0pt}\includegraphics[height=20pt]{../Artwork/logoVectoriel.png}}
#+LATEX:\fancyfoot[LO,RE]{\vspace{0pt}\includegraphics[height=20pt]{Images/logo_cnes.png}}
#+LATEX:\fancyfoot[C]{\vspace{3pt}\footnotesize{This content is provided under a Creative Commons Attribution 3.0 Unported License}\includegraphics[height=5pt]{Images/CC-licence.png}}
* How to build                                                     :noexport:
  - Use org-mode
  - You can generate pdf using org-babel
  - Solutions can be exclude from the tutorial using the ~exclude_tags~ export option
  - TODO LIST   
    - p.15 (section 3.2.3.3 item 1 et 2), les deux commandes OpticalCalibration : le nom du paramètre est -out et non -io.out
    - p.21 (section 3.3.3.2 item 4), commande compliquée avec la méthode connected component, qui implique des variables p1b4 par ex. Si j'en crois les extracts faits au début de la section 3.3, segmentation_small_xt_phr.tif est censée être une image à 3 bandes, et non 4; donc la commande ne peut pas fonctionner.
    - p.27 (section 3.3.3.4 item 1), l'image fait 4096x4096 et non 8192x8192 (voir extracts faits au début de la section 3.3)
    - p.56 (section 3.7.3.1 item 3), le nom du paramètre est -epi.elevation.avgdem.value et non -epi.elevation.avg.value
    - internationalisation
    - automatiser la génération des sorties avec des scripts intégrés dans org
* Foreword                                                               :fw:
** About the data

  The images used during these exercise are extracts from Pleiades
  demonstration products, made available for evaluation purpose. To
  get the full products please refer to this [[http://www.astrium-geo.com/fr/364-produits-de-demonstration][website]]. Products used
  are:
  - ~Pléiades Primary Product - Bundle~
  - ~Pléiades Ortho Product – Pan-sharpened~
  - ~Pleiades TRISTEREO Bundle PRIMARY~

  Those images are located on Melbourne, Australia and are covered by a CNES
  copyright.

  Exercises based on these Pleiades data include a set of
  command-line to generate the needed extracts.

  Other data needed for some exercises, as well as solution scripts
  can be found in the data package.
  
** About the software

   To perform the exercises, you will need to have the following
   software installed:
   - *Orfeo ToolBox* 4.2 or later, including applications
   - *Monteverdi2* 0.8 or later
   - *QGIS* 2.0 or later

     For *Orfeo ToolBox* and *Monteverdi* installation, you can refer to
     the installation from the [[http://www.orfeo-toolbox.org/packages/OTBSoftwareGuide.pdf][Orfeo ToolBox Cookbook]].

     For *QGIS* installation, please refer to *QGIS* documentation,
     which can be found on the project [[http://www.qgis.org/][website]].
   - *Monteverdi* 1.22 or later

#+INCLUDE: "licence.org"
* Exercises                                                            :exos:

#+INCLUDE: "mvd2apps.org" :minlevel 2
#+INCLUDE: "prepro.org" :minlevel 2
#+INCLUDE: "seg.org" :minlevel 2
#+INCLUDE: "features.org" :minlevel 2
#+INCLUDE: "classpix.org" :minlevel 2
#+INCLUDE: "classobj.org" :minlevel 2
#+INCLUDE: "stereo.org" :minlevel 2
#+INCLUDE: "sar.org" :minlevel 2
#+INCLUDE: "multitemp.org" :minlevel 2
#+INCLUDE: "mvdapps.org" :minlevel 2
