* Feature extraction                                               :features:
** Description
*** Abstract

     This workshop will introduce you to the *Feature Extraction*
     modules of *Monteverdi*. You will learn how to use these modules
     and visually evaluate the usefulness of different features for
     image information extraction.

*** Pre-requisites

     - Basic knowledge of *Monteverdi* usage

*** Achievements

     Being able to use the *Feature Extraction* modules of *Monteverdi*.

** Steps

*** Getting around the *Feature Extraction* modules

/Feature extraction/ is a generic term which refers to the procedure
of processing images in order to produce either new images or a set of
objects in order to represent the information contained by the
processed image in a higher level of abstraction.

Other terms than /features/ can be used as for instance /primitives/,
/indices/ or /descriptors/. Although minor differences in meaning
exist among these terms, we will use the as synonims here.

In *Monteverdi* there are 5 different modules for feature extraction
and they are all grouped under the /Filtering/$\rightarrow$/Feature
extraction/ menu.

All /Feature extraction/ modules follow the same rationale: they take
  an input image (with any number of channels) and produce an output
  image where each band is one of the computed features. 

In this part of the exercise, we will use the following data:

~phr_pxs_melbourne_xt_small.tif~

1. Open the image in *Monteverdi*.
2. Open the *Smoothing* module from the
   /Filtering/$\rightarrow$/Feature extraction/ menu, and load the
   image and the segmentation inside the module.
3. What are the 3 image windows which appear at the top of the
   graphical user interface?
4. The /Action/ tab is selected by default. What can you do on this
   part of the module?
5. Select the /Output/ tab and describe what can you do on it.

*** *Smoothing* module
You can either keep the /Smoothing/ module open from the previous
exercice or close it and open another one in order to start with a
fresh one.

1. One of the available features is /Original data/. What is it and
   what may its purpose be?
2. Select the /Mean/ feature and choose to compute it only on the
   /intensity/ channel. What is the meaning of the /Radius along X/
   and /Radius along Y/ parameters and what is their effect on the
   computed feature?
3. Select the /Meanshift smooth/ feature. And try to guess the meaning
   of the parameters and their influence on the results.
4. Select the /Meanshift clusters/ feature. As you can see, the same
   parameters as for the /Meanshift smooth are available/. Which is
   the difference in terms of the computed feature?
*** *Edge extraction* module
Open the /Edge extraction/ module and give it the input image. In
order to keep thing simple, you will only work with one channel. Also,
the /Harris detector/ -- which an interest point detector -- and the
/Touzi/ filter -- which is to be used with SAR images -- will be
ignored.

By reading text displayed on the /Feature Information/ window and the
list of available parameters and their effect on the computed
features, answer to the following questions.

1. What does the /Meanshift boundaries/ feature provide?
2. How can a /Variance/ filter detect edges?
3. What is the effect of the /sigma/ value on the /Recursive gradient/ filter?
4. In the /Sobel/ edge detection, the result is an edge density
   computed after the application of a Sobel edge enhancing filtering
   (high pas filter). You can set 2 different thresholds. What is
   their effect on the result?
*** *Radiometric index extraction* module

*** *Texture extraction* module

*** *Morphology* module

** Solutions                                            :features:solutions:

*** Getting around the *Feature Extraction* modules

**** Item 3
The graphical user interface displays a sub-sampled version of the
input image onn the left, the full resolution on the center and the
computed feature on the right. 

**** Item 4
The /Action/ tab allows you to select the feature to be computed,
decide on which channels the feature will be computed (if applicable),
set the parameters for the feature computation and see the list of
computed features. The /Add/ button effectively selects a given
feature for computation.

**** Item 5
The /Output/ tab allows you to decide which of the computed features
will be kept in the output image and in which order they will be
stored. 

*** *Smoothing* module

**** Item 1
The /Original data/ just copies the selected channels of the input
image as bands of the output image. This can be useful in the case
where you are creating a multi-channel image for a later
classification and you want to include some of the original bands,
side by side to other computed features.

**** Item 2
The radiuses define the size of a sliding window used to compute the
mean around every pixel of the image. The window will be a rectangle
centered on the pixel for which the mean is computed and sizes equal
to $2\times Radius_x +1$ in the horizontal direction and $2\times
Radius_y +1$ in the vertical one. The larger the radius the stronger
the smoothing.

**** Item 3
The /Meanshift smooth/ uses the mean-shift algorithm to smooth the
image. There are 2 main interests to this smoothing with respect to
the classical mean seen on the previous point:

1) edge preservation;
2) can be used on multi-channel images and take profit of
   inter-channel correlation.

This algorithm performs the smoothing simultaneously on the image
space (lines, columns) and on the feature space (for example, the
4-dimensional space defined by RGB+NIR images).

The meaning of the parameters is the following:
1. Spatial radius: the radius of the spatial window used for the smoothing.
2. Range radius: the radius of the smoothing window in the feature
   space.
3. Min. region size: the minimum size for a region to be kept in the
   clustering step (not used for the smoothing).
4. Scale: a multiplicative factor to be used for the image values
   which needs to be set if the image dynamics is low.

**** Item 4
The difference between the smoothing and the clustering is that the
latter produces an image which is piecewise constant. That is, an
image where connected pixels have the same value and form
regions. 

These regions are defined at the end of the smoothing procedure by
assigning each pixel the value of the mode of the histogram (in the
feature space) to which it belongs. Since these histograms are
computed also using a spatial window, the pixels belonging to the same
mode are close pixels in space. 

When clusters (a set of connected pixels associated with the same
histogram mode) define regions with sizes smaller than the minimum
region parameter, they are merged with the closest and most similar one.

*** *Edge extraction* module

**** Item 1
It's just the boundaries of the regions produced by the /Meanshift
clusters/ feature of the /Smoothing/ module.

**** Item 2
This filter assigns to each pixel the value of the local variance
inside a window centered on it:
$$ var(i,j) = \frac{1}{(2 Radius_x +1)\times(2 Radius_x +1)}\sum_{i-Radius_x}^{i+Radius_x}\sum_{j-Radius_y}^{j+Radius_y} \left(pix(i,j)-\mu(i,j)\right)^2$$
where $pix(i,j)$ is the input pixel value and $\mu(i,j)$ is the local
mean computed using the same window.

The variance values will be high when the pixel values inside the
window deviate from the local mean. This can happen in 2 cases:

1. When there is a strong texture effect.
2. When there are 2 or more regions inside the window with different
   mean values. This is the case when an edge is present.

**** Item 3
The recursive gradient uses a Gaussian smoothing (low pass filtering)
previous to gradient computation for edge detection. The /sigma/
parameter determines the width of the Gaussian smoothing, and
therefore the degree of blurring applied to the image before gradient
computation (edge detection).

The effect of the /sigma/ parameter will be the following: the larger
the value, the wider the edges and the fewer the over-detections due
to noise.

Therefore, the choice of the value of /sigma/ will depend on the noise
level of the image and on the kind of edges that one wants to detect.

**** Item 4
The lower and upper thresholds define the intervals of pixels which
will be set to 1 (below the lower and above the upper thresholds) or 0
(between the 2 thresholds) after the Sobel filtering and before the
edge density computation. Therefore, the thresholds determine how the
image produced by the Sobel filtering will be binarized before passing
it to the density computation (percentage of detected pixels inside
the window).
