** Extraction de primitives                                        :features:
*** Description
**** Résumé
Cet atelier présente les modules d'extraction de primitives
de *Monteverdi*. Vous apprendres à utiliser ces modules et à evaluer
visuellement l'utilité de différents types de primitives pour
l'extraction d'information des images.

**** Pré-requis
- Utilisation de *Monteverdi*

**** Objectifs
\^Etre capable d'utiliser les modules d'extraction de primitives de *Monteverdi*.

*** \'Etapes

**** Familiarisation avec les modules d'extraction de primitives

L'extraction de primitives est un terme générique qui fait référence
aux techniques de traitement des images qui permettent de produire de
nouvelles images ou des ensembles d'objets afin de représenter
l'information contenue par les images d'origine avec un niveau
d'abstraction plus élevé.

D'autres termes que /primitives/ peuvent être utilisés, comme par
exemple /indices/ ou /descripteurs/. Même s'il existe des différences
légères entre ces termes, nous les utiliserons comme des synonimes.

Dans *Monteverdi* il y a 5 modules pour l'extraction de primitives et
ils sont regroupés sous le menu /Filtering/$\rightarrow$/Feature extraction/.

Tous les modules d'extraction de primitives utilsent la même approche :
ils prennent une image en entrée (avec un nombre quelconque de bandes)
et produisent une image multi-canal où chaque composante est une des
primitives calculées.

Dans cette partie de l'exercice, vous utiliserez l'image 
~phr_xs_melbourne.tif~

1. Ouvrez l'image dans *Monteverdi*.
2. Ouvrez le module *Smoothing* à partir du menu
   /Filtering/$\rightarrow$/Feature extraction/ et choisissez l'image d'entrée.
3. A quoi correspondent les 3 images qui s'affichent dans l'interface?
4. L'onglet /Action/ est sélectionné par défaut. Que peut-on faire
   dans cette partie du module?
5. Allez dans l'onglet /Output/ et décrivez ce que l'on peut y faire.

**** Le module *Smoothing*
Vous pouvez garder le module ouvert dans l'exercice précédant ou le
fermer et en ouvrir un de nouveau.

1. Une des primitives disponibles est /Original data/. De quoi
   s'agit-il et quelle en est l'utilité?
2. Choisissez la primitive /Mean/ et calculez-la seulement sur
   l'intensité de l'image. A quoi correspondent les paramètres
   /Radius along X/ et /Radius along Y/ et quel est leur effet sur le résultat?
3. Choisissez la primitive /Meanshift smooth/. Essayez d'interpréter
   les paramètres et leur effet sur les résultats.
4. Sélectionnez la primitive /Meanshift clusters/. Les mêmes
   paramètres que pour /Meanshift smooth/ sont disponibles. Quelle est
   la différence entre ces 2 primitives?

**** Le module *Edge extraction*

Ouvrez le module /Edge extraction/ et donnez-lui une image
d'entrée. Pour rester simple, on ne travaillera qu'avec une seule
bande. Aussi les primitives /Harris detector/ -- points d'intérêt --
et /Touzi/ -- pour des images SAR -- seront ignorées.

Répondez aux questions suivantes en utilisant le texte affiché dans la
fenêtre /Feature Information/, la liste de paramètres pour chaque
primitive et leurs effets sur les résultats.

1. Quelle est l'information produite par la primitive /Meanshift boundaries/?
2. Comment peut-on détecter des contours avec un filtre de /Variance/?
3. Quel est l'effet du paramètre /sigma/ du filtre /Recursive gradient/?
4. Dans la primitive /Sobel/, le résultat est une densité de contours
   calculée après l'application d'un filtre de réhaussement de
   contours de Sobel. On peut utiliser 2 seuils différents. Quel est
   leur effet sur le résultat?

**** Le module *Radiometric index extraction*
Les indices radiométriques sont des combinaisons de bandes spectrales
qui permettent de mettre en évidence la présence de certains matériaux
ou types de couverture de la surface. Il existe des indices de
végétation, de sols, d'eau, de surfaces bâties, etc. Vous pouvez
trouver des descriptions détaillées et des références bibliographiques
à partir de la page sur les
[[http://wiki.orfeo-toolbox.org/index.php/Radiometric_Indices][indices
radiométriquee]] du wiki de l'Orfeo Toolbox.

1. Ouvrez le module /Radiometric index extraction/ et choisissez comme
   entrée l'image à 4 bandes. Choisissez /NDVI/ dans la liste
   /Vegetation/. Générez des résultats en utilisant différents choix
   pour les canaux (/Channels Selection/). Pourquoi le résultat est-il
   toujours le même indépendamment de ce choix?
2. Quelles sont les bandes spectrales les plus souvent utilisées pour
   les indices de végétation?
3. Trouvez une valeur pour le paramètre /s/ de MSAVI qui donne des
   résultats similaires à ceux du RVI. Quel est l'intérêt d'indices
   avec des paramètres par rapport à des indices qui n'en ont pas,
   comme le RVI ou le NDVI?
4. Quels indices d'eau ne peuvent pas être calculés pour une image
   Pléiades?

**** Le module *Texture extraction*

***** SFS
L'approche /Structural Feature Set/ calcule des textures en applicant
une analyse directionnelle à partir du pixel central de la fenêtre
d'analyse. Les directions sont calculées en utilisant un pas constant.

Une direction est définie comme : $$ \mathit{d_{i} = \sqrt{(m^{e1}-m{e2})^{2}+(n^{e1}-n{e2})^{2}}} $$

A partir de $\mathit{d_{i}}$, on définit des histogrammes :
 $$ \mathit{H(c) : \{c \in I \mid \lbrack d_{1}(c), \ldots , d_{i}(c),  \ldots , d_{D}(c)\rbrack  \}} $$

Enfin, 6 textures sont calculées :

 $$ \mathit{length = \max_{i \in \lbrack1; D\rbrack}(d_{i}(c)} $$
 $$ \mathit{width = \min_{i \in \lbrack1; D\rbrack}(d_{i}(c)} $$
 $$ \mathit{PSI = \frac{1}{D}\sum_{1=1}^{D}d_{i}(c)} $$
 $$ \mathit{\omega-mean = \frac{1}{D}\sum_{1=1}^{D}\frac{\alpha.(k_{i}-1)}{st_{i}}d_{i}(c)} $$
 $$ \mathit{ratio = \arctan{\frac{\sum_{j=1}^{n}{sort_{min}^{j}(H(c))}}{\sum_{j=1}^{n}{sort_{max}^{j}(H(c))}}}} $$
 $$ \mathit{SD = \frac{1}{D-1}\sqrt{\sum_{1=1}^{D}(d_{i}(c)-PSI)^{2}}} $$

1. En utilisant les paramètres par défaut, calculez les primitives
   $width$ et $length$. Expliquez les différences observées.
2. Quel est l'effet du seuil spectral sur le résultat? Même question
   pour le seuim spatial.

***** Haralick
Les textures de Haralick sont un ensemble d'indices calculés à partir
des matrices de co-occurrence en niveaux de gris. Ces matrices sont
calculées pour chaque pixel de l'image en niveaux de gris. Un
voisinage est défini par une fenêtre rectangulaire et son homologue
décalé d'un certain offset est aussi utilisé.

La matrice de co-occurrence $C$ définie sur un voisinage de $n x m$
pixels d'une image $I$ et avec un offset $(\Delta x,\Delta y)$ est
définie comme ceci :

#+BEGIN_LATEX
$$C_{\Delta x, \Delta y}(i,j)=\sum_{p=1}^n\sum_{q=1}^m
\begin{array}{cc}
1, & \mbox{if }I(p,q)=i\mbox{ and }I(p+\Delta x,q+\Delta y)=j \\ 
0, & \mbox{otherwise}
\end{array}$$
#+END_LATEX

Les valeurs des niveaux de gris sont quantifiées avec une certaine
précision (nombre de bins) de façon à ce que l'égalité entre les
valeurs soit probable.

Dans *Monteverdi*, il existe 2 versions des textures de Haralick. Nous
utiliserons seulement la 1ère.

1. Quel est le sens des paramètres /radius/, /offset/, /min\/max/ et /quant. levels/?
2. Calculez l'entropie de l'intensité de l'image pour des rayons
   différents (2, 3, etc.). Quel est l'effet de ce paramètre?
3. Calculez les indices /Energy/, /Entropy/, /Correlation/ et
   /Inertia/ avec les mêmes paramètres. Comparez-les et dites si
   certains vous paraissent rédondants.

*** Solutions                                          :features:solutions:

**** Familiarisation avec les modules d'extraction de primitives

***** Point 3
L'interface graphique affiche une version sous-échantillonnée de
l'image à gauche, la pleine résolution au centre et la primitive
calculée à droite.

***** Point 4
L'onglet /Action/ permet de sélectioner la primitive à calculer,
décider sur quels canaux elle sera calculée, choisir les paramètres de
la primitive et voir la liste des primitives calculées. Le boutton
/Add/ ajoute une primitive à la liste de droite.

***** Point 5
L'onglet /Output/ permet de choisir, parmi les primitives calculées,
quelles seront gardées en sortie et dans quel orde elles apparaîtront
sur l'image.

**** Le moule *Smoothing* 

***** Point 1
/Original data/ copie les canaux de l'image d'entrée choisis comme des
canaux des l'image de sortie. Ceci peut être utile dans le cas où l'on
souhaite créer une image pour réaliser des classifications et l'on
souhaite avoir des bandes d'origine en plus des primitives calculées.

***** Point 2
Les /radius/ définissent la taille de la fenêtre glissante qui sera
utilisée pour de calcul de la moyenne autour de chaque pixel. Il
s'agit d'une fenêtre rectangulaire centrée sur le pixel à traiter dont
la taille est de $2\times Radius_x +1$ pixels dans la direction
horizontale et $2\times Radius_y +1$ pixels dans la direction
verticale. Plus la taille de la fenêtre est grande, plus l'effet de
lissage est important.

***** Point 3
The /Meanshift smooth/ uses the mean-shift algorithm to smooth the
image. There are 2 main interests to this smoothing with respect to
the classical mean seen on the previous point:

1) edge preservation;
2) can be used on multi-channel images and take profit of
   inter-channel correlation.

This algorithm performs the smoothing simultaneously on the image
space (lines, columns) and on the feature space (for example, the
4-dimensional space defined by RGB+NIR images).

The meaning of the parameters is the following:
1. Spatial radius: the radius of the spatial window used for the smoothing.
2. Range radius: the radius of the smoothing window in the feature
   space.
3. Min. region size: the minimum size for a region to be kept in the
   clustering step (not used for the smoothing).
4. Scale: a multiplicative factor to be used for the image values
   which needs to be set if the image dynamics is low.

***** Point 4
The difference between the smoothing and the clustering is that the
latter produces an image which is piecewise constant. That is, an
image where connected pixels have the same value and form
regions. 

These regions are defined at the end of the smoothing procedure by
assigning each pixel the value of the mode of the histogram (in the
feature space) to which it belongs. Since these histograms are
computed also using a spatial window, the pixels belonging to the same
mode are close pixels in space. 

When clusters (a set of connected pixels associated with the same
histogram mode) define regions with sizes smaller than the minimum
region parameter, they are merged with the closest and most similar one.

**** *Edge extraction* module

***** Point 1
It's just the boundaries of the regions produced by the /Meanshift
clusters/ feature of the /Smoothing/ module.

***** Point 2
This filter assigns to each pixel the value of the local variance
inside a window centered on it:
$$ var(i,j) = \frac{1}{(2 Radius_x +1)\times(2 Radius_x +1)}\sum_{i-Radius_x}^{i+Radius_x}\sum_{j-Radius_y}^{j+Radius_y} \left(pix(i,j)-\mu(i,j)\right)^2$$
where $pix(i,j)$ is the input pixel value and $\mu(i,j)$ is the local
mean computed using the same window.

The variance values will be high when the pixel values inside the
window deviate from the local mean. This can happen in 2 cases:

1. When there is a strong texture effect.
2. When there are 2 or more regions inside the window with different
   mean values. This is the case when an edge is present.

***** Point 3
The recursive gradient uses a Gaussian smoothing (low pass filtering)
previous to gradient computation for edge detection. The /sigma/
parameter determines the width of the Gaussian smoothing, and
therefore the degree of blurring applied to the image before gradient
computation (edge detection).

The effect of the /sigma/ parameter will be the following: the larger
the value, the wider the edges and the fewer the over-detections due
to noise.

Therefore, the choice of the value of /sigma/ will depend on the noise
level of the image and on the kind of edges that one wants to detect.

***** Point 4
The lower and upper thresholds define the intervals of pixels which
will be set to 1 (below the lower and above the upper thresholds) or 0
(between the 2 thresholds) after the Sobel filtering and before the
edge density computation. Therefore, the thresholds determine how the
image produced by the Sobel filtering will be binarized before passing
it to the density computation (percentage of detected pixels inside
the window).
**** *Radiometric index extraction* module

***** Point 1
For the radiometric indices, the channel selection does not matter,
since each index is a particular combination of spectral bands. The
bands used are selected in the /Feature Parameters/ group.

***** Point 2
Most of the indices use the red (R) and the near infrared (NIR) bands,
since the vegetation has a low response on the R and high on the
NIR. Most indices use therefore combinations of differences and
ratios of these bands.

Sometimes, the green band is also used.
***** Point 3
Values greater than 6 should be fine.

The interest of having parameters is being able to take into account
soil reflectance for the cases of sparse vegetation. The /L/ parameter
of the SAVI index is close to 0 for very sparse vegetation and close
to 1 for a very dense cover. The /s/ parameter of the MSAVI index is
the slope of the soil line, that is the NIR reflectance plotted as a
function of the red reflectance for soil pixels.

***** Point 4
The NDTI and the NDWI can't be computed on a Pléiades image (or a
Quickbird image, for that matter) since the MIR (mid infrared, also
callwed SWIR for short-wave infrared) is not available.
In this case the NDWI2 index can be use.
**** *Texture extraction* module

***** SFS

****** Point 1
It may seem contradictory, but the $width$ feature gives hig values to
pixels which belong to elongated regions, while the $length$ feature
gives brigth values to any region (elongated or not) which has a large
area. If you have a look at the formulas for each feature you will
understand why.
****** Point 2
The spectral threshold sets the acceptable value of the difference
between 2 adjacent pixels along a line in order to continue adding new
pixels to the direction. Therefore, a small value for this thresholds
will produce shorter lines and therefore fewer pixels with bright
values.

The spatial threshold stops the length of the line in the given
direction regardless of the pixel values. Therefore, a low value for
this threshold will also produce shorter lines.
***** Haralick
****** Point 1
- The /radius/ parameter determines the size if the local window used
  for the co-occurrence matrix computation.
- The /offset/ parameter sets the $\Delta x$ and $\Delta y$ values for
  the co-occurrence matrix.
- The /min\/max/ values can be used to define the range of image
  values over which the quantification levels will be defined.
- The /quant. levels/ parameter defines the number of discrete values
  that will be used for comparing the pixel values in the
  co-occurrence matrix.
****** Point 2
The larger the radius, the wider the detected areas, since we are
introducing a kind of blurring of the computation by using larger windows.
****** Point 3
Visually, /Energy/ and /Entropy/ seem to be the most correlated, since
the pixel values are the most similar. However, if you have a closer
look, you will see that all 4 textures give the same kind of
information for typical remote sensign images. Although /Correlation/
and /Energy/ seem to be the most different because they present
different contrasts, they enhance the same areas as the other
textures.

Actually, Haralick textures are most useful for cases where
pseudo-periodic patterns appear and the texture parameters are well
suited. Otherwise, it is better to use 1st order statistics (as the
local variance) which are much more easy to compute and yield the same
kind of information.

