** Extraction de primitives                                        :features:
*** Description
**** Résumé
Cet atelier présente les modules d'extraction de primitives
de *Monteverdi*. Vous apprendrez à utiliser ces modules et à évaluer
visuellement l'utilité de différents types de primitives pour
l'extraction d'information des images.

**** Pré-requis
- Utilisation de *Monteverdi*

**** Objectifs
Être capable d'utiliser les modules d'extraction de primitives de *Monteverdi*.

*** Étapes

**** Familiarisation avec les modules d'extraction de primitives

L'extraction de primitives est un terme générique qui fait référence
aux techniques de traitement des images qui permettent de produire de
nouvelles images ou des ensembles d'objets afin de représenter
l'information contenue par les images d'origine avec un niveau
d'abstraction plus élevé.

D'autres termes que /primitives/ peuvent être utilisés, comme par
exemple /indices/ ou /descripteurs/. Même s'il existe des différences
légères entre ces termes, nous les utiliserons comme des synonymes.

Dans *Monteverdi* il y a 5 modules pour l'extraction de primitives et
ils sont regroupés sous le menu /Filtering/$\rightarrow$/Feature extraction/.

Tous les modules d'extraction de primitives utilisent la même approche :
ils prennent une image en entrée (avec un nombre quelconque de bandes)
et produisent une image multi-canal où chaque composante est une des
primitives calculées.

Dans cette partie de l'exercice, vous utiliserez l'image 
~phr_xs_melbourne.tif~

1. Ouvrez l'image dans *Monteverdi*.
2. Ouvrez le module *Smoothing* à partir du menu
   /Filtering/$\rightarrow$/Feature extraction/ et choisissez l'image d'entrée.
3. A quoi correspondent les 3 images qui s'affichent dans l'interface?
4. L'onglet /Action/ est sélectionné par défaut. Que peut-on faire
   dans cette partie du module?
5. Allez dans l'onglet /Output/ et décrivez ce que l'on peut y faire.

**** Le module *Smoothing*
Vous pouvez garder le module ouvert dans l'exercice précédant ou le
fermer et en ouvrir un de nouveau.

1. Une des primitives disponibles est /Original data/. De quoi
   s'agit-il et quelle en est l'utilité?
2. Choisissez la primitive /Mean/ et calculez-la seulement sur
   l'intensité de l'image. A quoi correspondent les paramètres
   /Radius along X/ et /Radius along Y/ et quel est leur effet sur le résultat?
3. Choisissez la primitive /Meanshift smooth/. Essayez d'interpréter
   les paramètres et leur effet sur les résultats.
4. Sélectionnez la primitive /Meanshift clusters/. Les mêmes
   paramètres que pour /Meanshift smooth/ sont disponibles. Quelle est
   la différence entre ces 2 primitives?

**** Le module *Edge extraction*

Ouvrez le module /Edge extraction/ et donnez-lui une image
d'entrée. Pour rester simple, on ne travaillera qu'avec une seule
bande. Aussi les primitives /Harris detector/ -- points d'intérêt --
et /Touzi/ -- pour des images SAR -- seront ignorées.

Répondez aux questions suivantes en utilisant le texte affiché dans la
fenêtre /Feature Information/, la liste de paramètres pour chaque
primitive et leurs effets sur les résultats.

1. Quelle est l'information produite par la primitive /Meanshift boundaries/?
2. Comment peut-on détecter des contours avec un filtre de /Variance/?
3. Quel est l'effet du paramètre /sigma/ du filtre /Recursive gradient/?
4. Dans la primitive /Sobel/, le résultat est une densité de contours
   calculée après l'application d'un filtre de rehaussement de
   contours de Sobel. On peut utiliser 2 seuils différents. Quel est
   leur effet sur le résultat?

**** Le module *Radiometric index extraction*
Les indices radiométriques sont des combinaisons de bandes spectrales
qui permettent de mettre en évidence la présence de certains matériaux
ou types de couverture de la surface. Il existe des indices de
végétation, de sols, d'eau, de surfaces bâties, etc. Vous pouvez
trouver des descriptions détaillées et des références bibliographiques
à partir de la page sur les
[[http://wiki.orfeo-toolbox.org/index.php/Radiometric_Indices][indices
radiométriquee]] du wiki de l'Orfeo Toolbox.

1. Ouvrez le module /Radiometric index extraction/ et choisissez comme
   entrée l'image à 4 bandes. Choisissez /NDVI/ dans la liste
   /Vegetation/. Générez des résultats en utilisant différents choix
   pour les canaux (/Channels Selection/). Pourquoi le résultat est-il
   toujours le même indépendamment de ce choix?
2. Quelles sont les bandes spectrales les plus souvent utilisées pour
   les indices de végétation?
3. Trouvez une valeur pour le paramètre /s/ de MSAVI qui donne des
   résultats similaires à ceux du RVI. Quel est l'intérêt d'indices
   avec des paramètres par rapport à des indices qui n'en ont pas,
   comme le RVI ou le NDVI?
4. Quels indices d'eau ne peuvent pas être calculés pour une image
   Pléiades?

**** Le module *Texture extraction*

***** SFS
L'approche /Structural Feature Set/ calcule des textures en appliquant
une analyse directionnelle à partir du pixel central de la fenêtre
d'analyse. Les directions sont calculées en utilisant un pas constant.

Une direction est définie comme : $$ \mathit{d_{i} = \sqrt{(m^{e1}-m^{e2})^{2}+(n^{e1}-n^{e2})^{2}}} $$

A partir de $\mathit{d_{i}}$, on définit des histogrammes :
 $$ \mathit{H(c) : \{c \in I \mid \lbrack d_{1}(c), \ldots , d_{i}(c),  \ldots , d_{D}(c)\rbrack  \}} $$

Enfin, 6 textures sont calculées :

 $$ \mathit{length = \max_{i \in \lbrack1; D\rbrack}(d_{i}(c)} $$
 $$ \mathit{width = \min_{i \in \lbrack1; D\rbrack}(d_{i}(c)} $$
 $$ \mathit{PSI = \frac{1}{D}\sum_{1=1}^{D}d_{i}(c)} $$
 $$ \mathit{\omega-mean = \frac{1}{D}\sum_{1=1}^{D}\frac{\alpha.(k_{i}-1)}{st_{i}}d_{i}(c)} $$
 $$ \mathit{ratio = \arctan{\frac{\sum_{j=1}^{n}{sort_{min}^{j}(H(c))}}{\sum_{j=1}^{n}{sort_{max}^{j}(H(c))}}}} $$
 $$ \mathit{SD = \frac{1}{D-1}\sqrt{\sum_{1=1}^{D}(d_{i}(c)-PSI)^{2}}} $$

1. En utilisant les paramètres par défaut, calculez les primitives
   $width$ et $length$. Expliquez les différences observées.
2. Quel est l'effet du seuil spectral sur le résultat? Même question
   pour le seuil spatial.

***** Haralick
Les textures de Haralick sont un ensemble d'indices calculés à partir
des matrices de co-occurrence en niveaux de gris. Ces matrices sont
calculées pour chaque pixel de l'image en niveaux de gris. Un
voisinage est défini par une fenêtre rectangulaire et son homologue
décalé d'un certain offset est aussi utilisé.

La matrice de co-occurrence $C$ définie sur un voisinage de $n x m$
pixels d'une image $I$ et avec un offset $(\Delta x,\Delta y)$ est
définie comme ceci :

#+BEGIN_LATEX
$$C_{\Delta x, \Delta y}(i,j)=\sum_{p=1}^n\sum_{q=1}^m
\begin{array}{cc}
1, & \mbox{if }I(p,q)=i\mbox{ and }I(p+\Delta x,q+\Delta y)=j \\ 
0, & \mbox{otherwise}
\end{array}$$
#+END_LATEX

Les valeurs des niveaux de gris sont quantifiées avec une certaine
précision (nombre de bins) de façon à ce que l'égalité entre les
valeurs soit probable.

Dans *Monteverdi*, il existe 2 versions des textures de Haralick. Nous
utiliserons seulement la 1ère.

1. Quel est le sens des paramètres /radius/, /offset/, /min\/max/ et /quant. levels/?
2. Calculez l'entropie de l'intensité de l'image pour des rayons
   différents (2, 3, etc.). Quel est l'effet de ce paramètre?
3. Calculez les indices /Energy/, /Entropy/, /Correlation/ et
   /Inertia/ avec les mêmes paramètres. Comparez-les et dites si
   certains vous paraissent redondants.

*** Solutions                                          :features:solutions:

**** Familiarisation avec les modules d'extraction de primitives

***** Point 3
L'interface graphique affiche une version sous-échantillonnée de
l'image à gauche, la pleine résolution au centre et la primitive
calculée à droite.

***** Point 4
L'onglet /Action/ permet de sélectionner la primitive à calculer,
décider sur quels canaux elle sera calculée, choisir les paramètres de
la primitive et voir la liste des primitives calculées. Le bouton
/Add/ ajoute une primitive à la liste de droite.

***** Point 5
L'onglet /Output/ permet de choisir, parmi les primitives calculées,
quelles seront gardées en sortie et dans quel ordre elles apparaîtront
sur l'image.

**** Le moule *Smoothing* 

***** Point 1
/Original data/ copie les canaux de l'image d'entrée choisis comme des
canaux des l'image de sortie. Ceci peut être utile dans le cas où l'on
souhaite créer une image pour réaliser des classifications et l'on
souhaite avoir des bandes d'origine en plus des primitives calculées.

***** Point 2
Les /radius/ définissent la taille de la fenêtre glissante qui sera
utilisée pour de calcul de la moyenne autour de chaque pixel. Il
s'agit d'une fenêtre rectangulaire centrée sur le pixel à traiter dont
la taille est de $2\times Radius_x +1$ pixels dans la direction
horizontale et $2\times Radius_y +1$ pixels dans la direction
verticale. Plus la taille de la fenêtre est grande, plus l'effet de
lissage est important.

***** Point 3
La primitive /Meanshift smooth/ utilise l'algorithme du mean-shift
afin de lisser l'image. Il y a 2 intérêts principaux à utiliser cet
algorithme par rapport à la moyenne glissante :

1) les contours sont préservés;
2) on peut l'appliquer à des images multi-canal et utiliser la
   corrélation entre canaux.

Cet algorithme effectue le lissage de façon simultanée dans l'espace
image (lignes, colonnes) et dans l'espace spectral (celui défini par
exemple par les bandes spectrales).

Voici la description des paramètres disponibles :

1. Spatial radius : le rayon de la fenêtre spatiale pour le lissage.
2. Range radius : le rayon de la fenêtre de lissage dans l'espace spectral.
3. Min. region size : la taille minimale pour qu'une région soit
   conservé dans le clustering (n'est pas utilisé dans le lissage).
4. Scale : facteur multiplicatif pour modifier les valeurs des pixels,
   ce qui est nécessaire quand la dynamique de l'image est faible.

***** Point 4
La différence entre le lissage et le clustering réside sur le fait que
ce dernier produit une image qui est constante par morceaux, c'est à
dire que les pixels qui appartiennent à une même région ont la même
valeur.

Ces régions sont définies à la fin du lissage en attribuant à chaque
pixel la valeur du mode de de l'histogramme auquel il appartient.

Quand des clusters (les régions associées au même mode) ont une taille
inférieure au minimum spécifié dans les paramètres, ils sont fusionnés
avec la région adjacente la plus similaire.

**** Module *Edge extraction*

***** Point 1
Il s'agit des contours des régions générées par la primitive
/Meanshift clusters/ du module /Smoothing/.

***** Point 2
Ce filtre associe à chaque pixel la valeur de la variance locale à
l'intérieur d'une fenêtre centrée sur celui-ci :

$$ var(i,j) = \frac{1}{(2 Radius_x +1)\times(2 Radius_x +1)}\sum_{i-Radius_x}^{i+Radius_x}\sum_{j-Radius_y}^{j+Radius_y} \left(pix(i,j)-\mu(i,j)\right)^2$$

où $pix(i,j)$ est la valeur du pixel d'entrée et $\mu(i,j)$ est la
moyenne locale calculée en utilisant la même fenêtre.

Les valeurs de variance seront élevées quand les pixels à l'intérieur
de la fenêtre s'éloignent de la moyenne locale. Ceci peut arriver dans
2 cas différents :

1. Quand il y a une texture très prononcée.
2. Quand il y a plusieurs régions dans la fenêtre avec des valeurs
   moyennes différentes. Ceci correspond au cas où un contour est présent.

***** Point 3
Le gradient récursif utilise un lissage gaussien (filtrage passe-bas)
préalable au calcul du gradient utilisé pour détecter les contours. Le
paramètre /sigma/ règle la largeur de la gaussienne utilisée pour le
lissage, c'est à dire le degré de flou.

L'effet de ce paramètre est le suivant : plus sa valeur est élevée,
plus les contours détectés seront larges et moins il y aura de fausses
détections dues au bruit.

La valeur de /sigma/ choisie dépendra donc du niveau de bruit de
l'image et du type de contours que l'on souhaite détecter.

***** Point 4
Les seuils haut et bas définissent les intervalles de valeurs qui
seront mis à 1 (à l'extérieur des seuils) ou à 0 (entre les 2 seuils)
après le filtrage de Sobel et avant le calcul de densité de
contours. Ces seuils déterminent donc comment le résultat du filtrage
de Sobel est binarisé.

**** Le module *Radiometric index extraction*

***** Point 1
Pour les indices radiométriques, la sélection des canaux à gauche n'a
pas d'influence, car chaque indice demande à ce que les bandes
spectrales utilisées soient sélectionnées dans la partie centrale de
l'interface (/Feature Parameters/).

***** Point 2
La plupart des indices de végétation utilisent la bande rouge (R) et
la bande proche infra-rouge (NIR), car la végétation a une faible
réponse dans le rouge et très forte dans le PIR. Beaucoup d'indices
utilisent donc des différences ou des ratios entre ces 2 bandes.

Parfois, la bande verte est aussi utilisée.

***** Point 3
Des valeurs supérieures à 6 devraient bien marcher.

L'intérêt d'avoir des paramètres est que l'on peut prendre en compte
la réfléctance du sol pour le cas de végétations peu denses. La
paramètre /L/ du SAVI est proche de 0 pour des végétations très
éparses et proche de 1 pour des végétations très denses. Le paramètre
/s/ du MSAVI est la pente de la droite des dols, c'est à dire, la
réflectance PIR en fonctions de la réflectance dans le rouge pour des
pixels de sol nu.

***** Point 4
Le NDTI et le NDWI ne peuvent pas être calculés avec des images
Pléiades (ou avec des images Quickbird ou Ikonos d'ailleurs) car le
moyen infra-rouge (MIR ou SWIR) n'est pas disponible. Dans ce cas, le
NDWI2 peut être utilisé.

**** Le module *Texture extraction* 

***** SFS

****** Point 1
Il peut paraître paradoxal, mais $width$ donne des valeurs élevées aux
pixels qui appartiennent à des régions longues, tandis que $length$
attribue des valeurs élevées à toute région (longue ou pas) qui a une
grande superficie. Les formules de chaque primitive permettent de
comprendre pourquoi.

****** Point 2
Le seuil spectral règle la valeur de la différence entre 2 pixels
adjacents le long d'une ligne qui peut être acceptée pour continuer à
calculer la longueur dans cette direction. Un faible valeur de ce
seuil produira donc des lignes plus courtes et donc moins de pixels
avec des valeurs élevées.

Le seuil spatial arrête l'analyse dans une direction indépendamment de
la valeur des pixels une fois qu'une certaine longueur est
atteinte. Une valeur faible produira aussi des lignes plus courtes.

***** Haralick
****** Point 1
- Le paramètre /radius/ définit la taille de la fenêtre locale
  utilisée pour le calcul de la matrice de co-occurrence.
- Le paramètre /offset/ fixe $\Delta x$ et $\Delta y$.
- Les valeurs /min\/max/ peuvent être utilisées pour définir la plage
  de valeurs sur laquelle la quantification sera réalisée.
- Le paramètre /quant. levels/ détermine le nombre de valeurs qui
  seront utilisées pour la quantification.

****** Point 2
Plus le rayon est grand, plus les zones détectées seront grandes, car
une sorte de lissage est introduit quand on utilise des fenêtres plus
grandes.

****** Point 3
Visuellement, l'énergie et l'entropie semblent très
corrélées. Cependant, à y regarder de plus près, on voit que les 4
textures donnent le même type d'information en général. Même si la
corrélation et l'énergie paraissent très différentes à cause de
l'inversion de contraste, elles mettent en évidence le même type de
zones.

En fait, les textures de Haralick sont utiles pour les zones avec des
motifs pseudo-périodiques et que l'on choisit les paramètres
correctement. Dans les autres cas, il est souvent plus judicieux
d'utiliser des statistiques de 1er ordre (comme la variance locale)
qui sont plus simples et plus rapides à calculer et qui donnent des
informations similaires.

