** *Monteverdi2* and *OTB applications*                             :mvd2apps:
*** Description
**** Abstract
     
     This exercise will get you familiar with the use of *Monteverdi2* and *OTB
     applications*.

     Monteverdi2 is the successor of the Monteverdi application which allows
     image visualization and to build processing based on OTB.

     The development started in 2012 with regular release and an iterative
     development process whit short loop which include user feedbacks.

     What's new (different from Monteverdi first version) in Monteverdi2?

     - GUI revamp: the software interface using the Qt toolkit
     - Modern viewer (navigation in resolutions, multiple color dynamic modes...)
     - Session manager : database manager to store all datasets and display parameters
     - Processing : interactive access to OTB application tools

     This tutorial is an adaptation of the one dedicated to Monteverdi and focus
     on Monteverdi2 main features.

**** Data
  
  If you need to generate the data used in this exercise from the
  original products, you can use the following command lines.
   
  #+LATEX:\begin{tiny}
  #+BEGIN_SRC bash
  $ otbcli_ExtractROI \
   -in ORTHO_UTM_PMS/IMG_PHR1A_PMS_001/IMG_PHR1A_PMS_201202250025599_ORT_IPU_20120504_1772-001_R1C1.JP2 \
   -out phr_pxs_melbourne.tif uint16 -startx 18432 -starty 4096 -sizex 4096 -sizey 4096

  $ otbcli_ExtractROI \
    -in PRIMARY_TRISTEREO_BUNDLE/IMG_PHR1A_MS_006/IMG_PHR1A_MS_201202250025599_SEN_IPU_20120509_2001-012_R1C1.JP2 \
    -out phr_xs_melbourne.tif uint16 -startx 4096 -starty 2048 -sizex 4096 -sizey 4084
  #+END_SRC
  #+LATEX:\end{tiny}
  
**** Pre-requisites

     - Basic knowledge of remote sensing and image processing,
       
**** Achievements

     - Visualize data in *Monteverdi2*,
     - Basic processing in *Monteverdi2* (rendering methods, access dataset and
       pixel information),
     - Basic processing with *OTB applications* in graphical mode

*** Steps
**** Monteverdi2: data opening and visualisation
     In this part of the exercise, you will use the following data:
     ~phr_pxs_melbourne.tif~

     1. Run *Monteverdi2*: open a terminal and run the following command:
        : $ monteverdi2    
     2. Open the image (use the /File/Import image...)
     3. After opening Monteverdi2, the application runs through the
           importation process before opening the application. In your opinion
           what are the main processing done by the application?
     4. Navigate into the image:
        1. Change the full resolution displayed area using the QL window
        2. Change the zoom level,
        3. How to navigate through resolution in Monteverdi2?
     5. Using the dataset properties widget
        1. What is the image size?
        2. What is the meaning of the information "Block size"?
     6. Using the Pixel description widget
        1. What are the information displayed about the current pixel under mouse pointer ?
        2. How to know in Monteverdi2 if the image displayed is georeferenced?
     7. Using the Color video setup widget
        1. Change set-up to visualize the 4th band,
        2. Change set-up to visualize in false color mode (screen red:
           near infra-red channel, screen green: red channel, screen
           blue: green channel).
        3. Change set-up to come back to natural colors
     8. Using the Dataset widget:
        1. What is the image size?
     9. Using the preferences widget
        1. Monteverdi2 allows to specify a directory containing DEM
           information. Can you give one example of RS processing where a DEM is needed?
        
     _Tips and Recommandations:_
     - Starting with Monteverdi2 0.7 you need to press Ctrl and use the mouse
       wheel to navigate through image resolution,
     - Pleiades bands order is red channel, green channel, blue
       channel, near infra-red channel.

**** Monteverdi2: basic rendering functions and histogram visualization
     #+LABEL:   ex1_monteverdi2_basic_rendering
     In this part of the exercise, you will use the following data:

     ~phr_xs_melbourne.tif~

     1. What are the 3 different ways to change the rendering threshold?
     2. What is the behaviour when you move the cursor of the gamma correction widget?
     3. What is the purpose of the "No data" setup?

**** OTB applications: Graphical and command-line mode

     1. Run the following command:
        : $ otbcli_OrthoRectification
        then
        : $ otbgui_OrthoRectification
        and then searh for the Orthorectification application from the applications 
        What do you observe ?
     2. How many *OTB applications* are currently available ?
     3. How can you get help and documentation about applications ?

**** OTB applications in Monteverdi2: Basic processing
     
     In this part of the exercise, you will use the following data:

     ~phr_xs_melbourne.tif~

     1. Open the image in *Monteverdi2*.
     2. Find the /BandMath/ application in the menu. Import the image in
        this module. What kind of processing is offered ?
     3. Using this module, compute the NDVI of the image: 
        #+LATEX:\begin{equation}
        NDVI = \frac{NIR-RED}{NIR+RED}
        #+LATEX:\end{equation}

     4. What is the path of the output image file?
     5. Visualize the output in Monteverdi2
     6. Using this application, build a mask of pixels whose Digital Number (DN) in the NIR
        channel is lower than 150. Switch between the input image and the
        mask.
     7. Using this application, build a mask of pixels whose DN is upper
        than 1000 in all spectral bands.
     8. Using the /Images concatenation/ app, build a composite RGB image
        with the mask of high values in the red channel, the mask of
        low NIR values in the blue channel and the NDVI in the green
        channel.
     9. Using the /Color Mapping/ app, build a composite RGB image
        of the NDVI that allows for better image interpretation.

     _Tips and Recommandations:_
     - NDVI values are within -1 and 1, but the range can be much
       more narrow.
     - Import dataset as input of applications by drag and drop inside the
       applications widget

**** Homework
     
     1. Is it possible to load or visualize images directly from command-line
        using *Monteverdi2* ?
     2. What is the geoid?
     3. Is there another way to compute radiometric indices like NDVI
        with the *OTB Applications* ?
     4. Learn about the /Python/ access to *OTB Applications* and
        write a python script performing the same steps as in section
        [[OTB applications in Monteverdi2: Basic processing]]
        
*** Solutions                                                     :solutions:
    
**** Monteverdi2: data opening and visualisation

**** Monteverdi: basic rendering functions

**** OTB applications: Graphical and command-line mode

**** OTB applications in Monteverdi2: Basic processing

**** Homework
