** *Monteverdi* et *OTB applications*                               :mvdapps:
*** Description
**** Résumé

Cet exercice permet de se familiariser avec l'utilisation
de *Monteverdi* et les outils disponibles dans *OTB Applications*.

**** Pré-requis

- Connaissances de base en télédétection et traitement des images
- Être capable de lancer des programmes en ligne de commande

**** Objectifs

- Visualisation de données dans *Monteverdi*
- Traitements simples avec *Monteverdi*
- Traitements simples avec *OTB Applications* en mode graphique
- Traitements simples avec *OTB Applications* en ligne de commande

*** Étapes

**** Monteverdi: lecture de données et visualisation
Dans cette partie de l'exercice, l'image suivante sera utilisée :
~phr_pxs_melbourne.tif~

1. Lancement de *Monteverdi* : ouvrir un terminal et taper
   : $ monteverdi    
2. Ouvrir l'image (avec le menu /File/Open dataset/)
3. Trouver une façon d'afficher l'image (il y a 2 façons de faire).
4. Se déplacer dans l'image :
   1. Changer la zone affichée à pleine résolution;
   2. Changer la zone affichée dans la fenêtre de zoom;
   3. Changer le niveau de zoom;
   4. Quelles sont les informations affichées à propos du pixel qui se
      trouve sous le pointeur de la souris?
5. À l'aide du panneau de configuration de la visualisation dans
   l'onglet /Setup/ :
   1. Changer la configuration pour visualiser la 4ème bande;
   2. Affichage en fausses couleurs (mettre le proche infra-rouge dans
      l'affichage rouge, la bande rouge dans l'affichage vert et la
      bande verte dans l'affichage bleu);
   3. Changer la configuration pour revenir à un affichage en couleurs naturelles;
   4. Améliorer le contraste en utilisant la zone à pleine résolution;
   5. Améliorer le contraste en utilisant la zone de zoom;
   6. Revenir aux ajustements de contraste par défaut.
        
_Trucs et astuces:_
 - Les flèches du clavier peuvent être utilisées pour naviguer dans les images.
 - L'ordre des bandes Pléiades est : rouge, vert, bleu et proche infra-rouge.

**** Monteverdi : traitements basiques
#+LABEL:   ex1_monteverdi_basic_processing
Dans cette partie l'image suivante est utilisée :

~phr_xs_melbourne.tif~

1. Ouvrez l'image dans *Monteverdi*.
2. Trouvez le module /BandMath/ dans les menus. Ouvrez l'image dans ce
   module. Quel type de traitement est proposé?
3. À l'aide de ce module, calculez le NDVI de l'image :
   #+LATEX:\begin{equation}
   NDVI = \frac{PIR-Rouge}{PIR+Rouge}
   #+LATEX:\end{equation}
4. En utilisant le même module, créez un masque des pixels dont la
   valeur dans le PIR est inférieure à 150. Affichez l'image et le
   masque dans le même /viewer/
5. Créez un masque correspondant aux pixels dont la valeur est
   supérieure à 1000 dans toutes les bandes spectrales. Visualisez le
   masque et l'image dans le même /viewer/.
6. Utilisez le module /Concatenate/ afin de créer une image RVB
   composite avec le masque des valeurs élevées dans le rouge, le
   masque des valeurs faibles de PIR dans le bleu et le NDVI dans le
   vert.
7. Utilisez le module /Color Mapping/ afin de créer une image
   composite RVB du NDVI qui permet une meilleure interprétation
   visuelle.

_Trucs et astuces :_
- Les valeurs du NDVI sont comprises entre -1 et +1, mais la vraie
  dynamique des valeurs observées peut être beaucoup plus faible.

**** OTB applications : mode graphique et ligne de commande
1. Lancez la commande suivante :
   : $ otbcli_OrthoRectification
   et ensuite
   : $ otbgui_OrthoRectification
   Qu'observez-vous?
2. Combien d'applications sont actuellement disponibles dans *OTB Applications*?
3. Comment peut-on obtenir de l'aide et de la documentation à propos
   des applications?

**** OTB applications : traitements simples
Utilisez les applications afin de reproduire les résultats des étapes
3 à 7 de la section sur Monteverdi [[Monteverdi : traitements basiques]].
     
**** Pour aller plus loin
1. Comment peut-on lire ou visualiser des images directement depuis la
   ligne de commande avec *Monteverdi*?
2. Y-a-t'il d'autres façons de calculer des indices comme le NDVI avec
   les *OTB Applications*?
3. Renseignez-vous sur l'utilisation des *OTB Applications* depuis
   /Python/ et écrivez un script en /Python/ qui réalise les mêmes
   traitements que dans la section [[OTB applications : traitements simples]]
     
*** Solutions                                                     :solutions:

**** Monteverdi: lecture de données et visualisation

***** Point 3
Pour visualiser une image dans *Monteverdi*, vous pouvez :
- soit faire clic droit sur l'image et sélectionner /Display in viewer/,
- soit utiliser le menu /Visualization/Viewer/, choisir l'image et
  cliquer sur /OK/.

La 2è option permet de visualiser plusieurs images simultanément.

***** Point 4
La zone en bas à gauche affiche des informations sur l'image et sur le
pixel qui se trouve sous le pointeur de la souris :
- la position courante dans l'image,
- la taille de l'image,
- la bande affichée,
- les valeurs des pixels,
- la résolution (spacing),
- la position géographique si elle est disponible,
- le nom de l'endroit s'il est disponible.

**** Monteverdi : traitements basiques

***** Point 2
Le module *BandMath* permet de faire des calculs avec les bandes des
images en utilisant la syntaxe de [[http://muparser.sourceforge.net/][muParser]].

***** Point 3
Afin de calculer le NDVI, on peut utiliser l'expression *BandMath*
suivante :
: (im1b4-im1b1)/(im1b4+im1b1)

***** Point 4
Afin de construire le masque des pixels dont le compte numérique dans
le PIR est inférieur à 150, on peut utiliser l'expression *BandMath*
suivante :
: if(im1b4<150,255,0)

***** Point 5
Pour générer le masque des pixels dont le compte numérique est
supérieur à 1000 dans toutes les bandes spectrales, on peut utiliser
l'expression *BandMath* suivante :

: if(min(im1b1,im1b2,im1b3,im1b4)>1000,255,0)

***** Point 6
Dans la barre de menu, choisir /File/Concatenate images/ et choisir
les sorties des 3 modules *BandMath*. L'image résultante peut être
affichée dans le /Viewer/ et elle ressemble à ceci :

#+Latex:\vspace{0.5cm}
#+Latex:\begin{center}
#+ATTR_LaTeX: :width 0.9\textwidth
file:Images/bandmath.png]]
#+Latex:\end{center}

***** Point 7
Dans la barre de menu, choisir /Visualisation/Color Mapping/ et
charger la sortie du NDVI calculé avec le
module *BandMath*. Sélectionner une plage de valeurs entre -0.2 et 0.7
et utiliser la table de couleurs /Jet/. Voici le résultat tel
qu'affiché par le /Viewer/ :

#+Latex:\vspace{0.5cm}
#+Latex:\begin{center}
#+ATTR_LaTeX: :width 0.9\textwidth
file:Images/colormapping.png]]
#+Latex:\end{center}

**** OTB applications : mode graphique et ligne de commande

***** Point 1
La première commande lance la version en ligne de commande de
l'application *Orthorectification*. La deuxième commande en lance la
version avec IHM graphique.
      
***** Point 2
Il y a 59 applications dans la version 3.14.1 de l'OTB.

***** Point 3
Il existe plusieurs façons d'obtenir de l'aide et de la documentation :
- Le lancement d'une application en ligne de commande sans paramètres
  affiche une courte description de l'application et de ses
  paramètres. Un lien vers la documentation complète
  [[http://www.orfeo-toolbox.org][sur le site de l'OTB]] est aussi affiché.
- La version graphique des applications dispose d'un onglet
  /Documentation/ où une description détaillée est donnée.
- Enfin, une documentation très complète sur les applications est
  disponible dans l'[[http://www.orfeo-toolbox.org/CookBook/][Orfeo ToolBox Cookbook]].

**** OTB applications : traitements simples

***** Point 1
Voici l'ensemble des commandes à utiliser :
   
D'abord, nous calculons le NDVI avec l'application *BandMath* :
: $ otbcli_BandMath -il phr_xs_melbourne.tif
:   -out ndvi.tif float -exp "(im1b4-im1b1)/(im1b4+im1b1)"

Ensuite, nous calculons le masque pour PIR < 150 :
: $ otbcli_BandMath -il phr_xs_melbourne.tif
:   -out lownir.tif uint8 -exp "if(im1b4<150,255,0)"

Puis, nous calculons le masque des pixels dont toutes les bandes sont
supérieures à 1000 :
: $ otbcli_BandMath -il phr_xs_melbourne.tif
:   -out high.tif uint8 
:   -exp "if(min(im1b1,im1b2,im1b3,im1b4)>1000,255,0)"

Notez que pour générer des masques, un type de pixel /uint8/ (entier
codé en 8 bits) est suffisant, tandis que pour le calcul du NDVI, un
codage en flottant est nécessaire.

Nous pouvons maintenant concaténer tous ces résultats dans une seule
image : 
: $ otbcli_ConcatenateImages -il high.tif ndvi.tif lownir.tif 
:   -out map1.tif float

Enfin, nous appliquons la palette de couleurs au NDVI comme ceci :

: $ otbcli_ColorMapping -in ndvi.tif -out map2.png uint8 
:   -method continuous -method.continuous.min -0.2 
:   -method.continuous.max 0.7 -method.continuous.lut jet

**** Pour aller plus loin
***** Point 1
A partir de la ligne de commande, lancer
: $ monteverdi -in  phr_xs_melbourne.tif
ouvrira l'image dans *Monteverdi* et l'affichera dans le module de
visualisation, et
: $ monteverdi -il  phr_xs_melbourne.tif ndvi.tif
permet d'ouvrir plusieurs images dans *Monteverdi*.

***** Point 2
L'application *RadiometricVegetationIndices* permet de calculer
plusieurs indices de végétation dont le NDVI.
      
***** Point 3
Vous pouvez consulter ce
[[http://www.orfeo-toolbox.org/CookBook/CookBooksu7.html#x16-170001.3.4][chapitre]] 
du *Cookbook* afin de vous documenter sur l'interface /Python/.
     
